config/routes.rb
TotApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',        to: 'users#new',                  via: 'get'
  match '/signin',        to: 'sessions#new',               via: 'get'
  match '/signout',       to: 'sessions#destroy',           via: 'delete'
  match '/about',         to: 'static_pages#about',         via: 'get'
  match '/contact',       to: 'static_pages#contact',       via: 'get'
  match '/course',        to: 'static_pages#course',        via: 'get'
  match '/event_details', to: 'static_pages#event_details', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :user_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      flash[:success] = 'Logged in!'
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
  	render 'new'
    end
  end

  def destroy
  	sign_out
  	flash[:success] = 'You are now logged out!'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def course
  end

  def event_details
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
  	@users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Tour of Tauranga!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:user_name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Tour of Tauranga"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.user_name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<p>   
<small>
      	<%= link_to image_tag("FindUsOnFB-144.png", alt: "Facebook" ), 'http://facebook.com/touroftauranga', :target=>"_blank" %>      	
      </small>
        <center>&nbsp;&nbsp;&nbsp;&nbsp;<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.touroftauranga.co.nz&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=lucida+grande&amp;height=80&amp;appId=412659185421408" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe></center><br><br>
      <p>
  <small>
    <a><%= link_to image_tag("msbop.png", alt: "BOPMS"), 'http://bopms.co.nz/',:target=>"_blank" %></a>
  </small>
  <br>
  <ul>
  	<li>
      <%= link_to "About",   about_path %>
  	</li>
  </ul>
  <br>
    <copyright>
      <p1>&copy;Copyright 2014. BOP MS Society. All rights reserved.</P1>&nbsp;&nbsp;&nbsp;&nbsp;
    </copyright>
 </footer>    



app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
         <nav> 
         <h10>"Life is a journey......enjoy the ride"</h10>
          
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Course Map",    course_path %></li>
             <% if signed_in? && current_user.admin? %>
              <li><%= link_to "Admin",    event_details_path %></li>
            <% end %>
            <li><%= link_to "Event Details",    event_details_path %></li>
               <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
</header>
              

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <%= favicon_link_tag 'favicon.ico' %> 
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="center hero-unit">

<%= link_to image_tag("tour_of_tauranga_logo.gif", alt: "BOPMS"), 'http://bopms.co.nz/' %><h7>About Us</h7>
  <h7>
	The Tour of Tauranga is an annual event to raise funds for <br>
	<a href="http://bopms.co.nz/">Bay of Plenty Multiple Sclerosis Society (BOPMS)</a><br>
  </h7>

	<div class="row">
		
		
			<h21>For all enquiries, please contact:</h21>
			<address>
			<strong>BOP MS SOCIETY</strong><br>
			TAURANGA<br>
			Rachelle - 021 255 2733<br>
			Pat - 021 482 643<br>
			<br>
			<h21>Email: <a href="mailto:touroftauranga@gmail.com">touroftauranga@gmail.com</a>
			</address></h21>
			<h21>Website by Greg Standring <a href="mailto:standringg@gmail.com">standringg@gmail.com</a></h21><br><h21> Many thanks to <a href="http://littlegiant.co.nz/">Little Giant</a> Digital Design for graphics used on this site. </h21>
	</div>

 

app/views/static_pages/course.html.erb
<% provide(:title, 'Course') %>
<div class="center hero-unit">
<h1>Tour of Tauranga</h1>
<br>
<h7>
   Welcome to our course page for the 
   premiere fundraising event for<br>
   <a href="http://bopms.co.nz/">Bay of Plenty Multiple Sclerosis Society (BOPMS)</h7>

 <h1>  <%= image_tag("route-map.gif", alt: "Tour of Tauranga Route Map")%>
 </h1>

app/views/static_pages/event_details.html.erb
<% provide(:title, 'Event Details') %>
<div class="center hero-unit">
<h1>Event Details</h1><br>
<h7>
Edgewater Fan on the Strand, Downtown Tauranga
<br>
Sunday 9 November 2014.
<br>
<r>Entry Fees</r>
<br>
<r>On the day entries are available - cash only</r>
<br>
Individual $20.00  
<br>
Family (2 adults + 2 under 14) $50.00 
<br>
Extra child (5 - 14) $5.00
<br>
<r>Early Bird (before October 7)</r>
<br>
Individual $15.00
<br>
Family (2 adults + 2 under 14) $40.00
<br>
Extra child (5 - 14) $5.00
<br>
<r>--------------------</r>
<br>
Registrations from 7.30am / Start 9am
<br>
Prize giving /Spot Prizes 12:00pm
</h7>
<br>
<small>
	<r>PLEASE NOTE: Suitable for mountain bikes and commuter bikes. Sorry not suitable for road bikes.</r>
</small>
<br>
<br>
<left2>
	<center><r>
	Enter before the 7th of October and you will be in the draw to win a Xmas camp fitness <br><br><br>package from <a><%= link_to "Life Personal Fitness", "http://www.lifepersonalfitness.co.nz", :target =>"_blank"%></a> valued at $350!
    </r></center>
	<h2>
	<br>
    <%= link_to "Enter now", "http://www.givealittle.co.nz/search/?q=Tour+of+tauranga&Search=go", class: "btn btn-large btn-primary" , :target =>"_blank"%>
    <small><r>at Givealittle (please use the <b>Donate now ></b> button and use the comments and display name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fields for your entry details, and <strong>bring your e-reciept on the day (essential)</strong> )</r></small>
    </h2>
	Enjoy a scenic ride around Taurangas great cycleways, explore the quiet parks and lovely waterways. Get out on your bikes this spring for a leisurely 25km (or 12km) bike ride. The <a><%= link_to"course", course_path %></a> is unique, safe, and guaranteed to be enjoyed, with great spot prizes to be won, all in support of the BOP Multiple Sclerosis Society.
    <br>
    <br>
	Please get your bikes checked at <a><%= link_to "Redbike Mt Maunganui", "http://www.redbike.net.nz/", :target =>"_blank"%></a> (this is free of charge) prior to the day to make sure your bike is in a safe working order. We are very fortunate to have some great sponsors and prizes so stay around after the ride to be in the draw for some fantastic spot pizes.
    <br>
    <br>
</left2>
<left1>
	<h7>
		A great big thanks to our kind supporters:
	</h7>
<br>
	Sthil Mt Maunganui - 
	<a><%= link_to"www.stihlshop.co.nz","http://www.stihlshop.co.nz/", :target =>"_blank" %></a>
<br>
	SunMedia - 
	<a><%= link_to"www.sunlive.co.nz","http://www.sunlive.co.nz/", :target =>"_blank" %></a>
<br>
	The Hits - <a><%= link_to"www.thehits.co.nz","http://www.thehits.co.nz/", :target =>"_blank"%></a>
<br>
	Hedgehog Bikes - <%= link_to"www.hedgehogbikes.co.nz","http://www.hedgehogbikes.co.nz/", :target =>"_blank"%></a>
<br>
	Countdown Cameron Rd &amp; Fraser Cove - <%= link_to"www.countdown.co.nz", "http://www.countdown.co.nz", :target =>"_blank"%></a>
<br>
	Life Personnel Fitness - <%= link_to"www.lifepersonalfitness.co.nz","http://www.lifepersonalfitness.co.nz", :target =>"_blank"%></a>
<br>	
	Tasti - <%= link_to"www.tasti.co.nz","http://www.tasti.co.nz/", :target =>"_blank"%></a>
<br>
	Tauranga City Council - <%= link_to"www.tauranga.govt.nz","https://www.tauranga.govt.nz/", :target =>"_blank"%></a>
<br>
	Mills Reef Winery - <%= link_to"www.millsreef.co.nz", "http://www.millsreef.co.nz/", :target =>"_blank"%></a>
<br>
	The Warehouse Fraser Cove - <%= link_to"www.thewarehouse.co.nz", "http://www.thewarehouse.co.nz/is-bin/INTERSHOP.enfinity/WFS/TWL-B2C-Site/en_NZ/-/NZD/ViewFindAStore-Store?RegionID=4&StoreID=Fraser+Cove&Region=Bay+of+Plenty", :target =>"_blank"%></a>
<br>
	Payless Plastics - <%= link_to"www.paylessplastics.kiwi", "http://paylessplastics.kiwi/", :target =>"_blank"%></a>
<br>
	The Gym Tauranga - <%= link_to"www.thegym.co.nz", "http://www.thegym.co.nz/", :target =>"_blank"%></a> 
<br>
	<h7>
		Please support these local businesses!
	</h7>
<br>
<br>
<br>
</left1>

app/views/static_pages/home.html.erb
<div class="center jumbotrom">
  <%= image_tag("tour_of_tauranga_logo.gif", alt: "BOPMS") %>
  <h7><br><br>
	Welcome to our home page for the Tour of Tauranga, <br>the
	premiere fundraising event for <br>
	<a href="http://bopms.co.nz/">Bay of Plenty Multiple Sclerosis Society (BOPMS)</a>
  </h7><br><br>
  
  

<h7>Event Date: Sunday 9 November 2014 <br>
	Registration 7.30-8.30am / Start 9am <br>at Herries Park, downtown Tauranga on the Strand</h7>
	<br><br>
	<%= link_to image_tag("herries_park.jpg", alt: "BOPMS"), 'http://bopms.co.nz/' %>
	<br><br>
	
	
	<h8>Tips for the Day<br><br>Bring a drink and snacks, there are plenty of rest stops along the way <br>Dress for the weather - bring a warm layer <br>Bring a camera <br>Bring your family and friends and have some fun!</h8><br><br>
    
    <rb>
	Register before the 7th of October and you will be in the draw to win a Xmas camp fitness <br>package from <a><%= link_to "Life Personal Fitness", "http://www.lifepersonalfitness.co.nz", :target =>"_blank"%></a> valued at $350!</rb>
	
	
  <%= link_to "Event Details & Entry", event_details_path, class: "btn btn-large btn-primary" %>
  
	
	
	
	
	

app/views/users/_user.html.erb
<li><left>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.user_name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</left></li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="center hero-unit">
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :user_name, "New User Name" %>
      <%= f.text_field :user_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Suporters') %>
<div class="center hero-unit">
<h1>Suporters</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="center hero-unit">
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :user_name %>
      <%= f.text_field :user_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<div class="center hero-unit">
<div class="row">
  <aside class="span4">
    <section>
      <h9>
        <%= gravatar_for @user %>
	    <%= @user.user_name %>
      </h9>
    </section>
  </aside>
</div>